version: '3.3'
services:
  redis:
    image: redis:-alpine
    volumes:
      - ./redis:/data
    command: redis-server --appendonly yes
  chromium:
    image: 'alpeware/chrome-headless-trunk'
    volumes:
      - ./chromium/data:/data alpeware/chrome-headless-trunk
  prerender:
    depends_on:
      - chromium
    links:
      - chromium
    build: prerender
    command: npm run-script dev
    volumes:
        - ./prerender/tmp/:/tmp/prerender
        - ./prerender:/usr/src/app
    environment:
      NODE_ENV: "development"
      env: 'development'
      port: 3000
      chromium: "http://chromium:9222"
      target: 'https://pallco.com.mx/'
      cache: 0
    ports:
      - "3000:3000"


  






